import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "UMALLC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png" />
          
          {/* Favicons */}
          <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png" />
          <link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
          
          
          {/* Additional Favicon Sizes for Android */}
          <link rel="icon" type="image/png" sizes="192x192" href="/images/android-chrome-192x192.png" />
          <link rel="icon" type="image/png" sizes="512x512" href="/images/android-chrome-512x512.png" />
      </head>
      <body className={`font-inconsolata`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
